variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: ""
  BACKEND_IMAGE: registry.gitlab.com/dci-project/arqsoft-dci/proyectos/1s2024/scanimal/sca-api:latest

stages:
  - build
  - deploy

build-backend:
  stage: build
  image: docker:24.0.5
  services:
    - docker:24.0.5-dind
  variables:
    DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
  script:
    - echo $CI_REGISTRY_PASSWORD | docker login -u $CI_REGISTRY_USER --password-stdin $CI_REGISTRY
    - docker build -t $BACKEND_IMAGE $CI_PROJECT_DIR
    - docker push $BACKEND_IMAGE
  only:
    - develop

deploy:
  stage: deploy
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo $SERVER_IP_DEV
    - ssh-keyscan $SERVER_IP_DEV >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - scp $CI_PROJECT_DIR/docker-compose.yml $SERVER_USER_DEV@$SERVER_IP_DEV:~/sca-api/
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY"
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "docker-compose --file ~/sca-api/docker-compose.yml down --remove-orphans"
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "docker system prune -f"
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "docker images -q | grep -v $(docker images -q postgres) | xargs -r docker rmi -f"
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "docker pull "$BACKEND_IMAGE""
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "docker-compose --file ~/sca-api/docker-compose.yml up -d"
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "docker-compose --file ~/sca-api/docker-compose.yml up -d"
    - ssh $SERVER_USER_DEV@$SERVER_IP_DEV "rm -rf ~/sca-api/docker-compose.yml"
  
  only:
    - develop
